// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RihalProject.Data;

namespace RihalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RihalProject.Models.classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("class_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("RihalProject.Models.countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RihalProject.Models.students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("class_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("classesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("countryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("country_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("modified_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("classesId");

                    b.HasIndex("countryId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("RihalProject.Models.students", b =>
                {
                    b.HasOne("RihalProject.Models.classes", "classes")
                        .WithMany("students")
                        .HasForeignKey("classesId");

                    b.HasOne("RihalProject.Models.countries", "country")
                        .WithMany("students")
                        .HasForeignKey("countryId");

                    b.Navigation("classes");

                    b.Navigation("country");
                });

            modelBuilder.Entity("RihalProject.Models.classes", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("RihalProject.Models.countries", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
